### ISSUE TITLE
Segmentation Fault: If required privileges are not given to the pg1-user, results in SegFault

### ISSUE THREAD

**Issue by insafk** [pgbackrest/pgbackrest#1173]
1. pgBackRest version: 2.29(Also tried in 2.28)

2. PostgreSQL version: 11.4

3. Operating system/version: Tried in both CentOS and Ubuntu. (BackupServer-CentOS DBServer-CentOS and BackupServer-Ubuntu DBserver-Ubuntu)

4. Did you install pgBackRest from source or from a package? source

5. Please attach the following as applicable:  attached at the end

6. Describe the issue:

Getting Segmentation Fault if the pg1-user doesn't have required privileges, to be specific, I missed to give `GRANT pg_read_all_settings to backup_user`. 
After granting all required privileges, **it is working fine**. So just wanted to let you know regarding this bug.

### Check command
```shell
pgbackrest --stanza=demo --log-level-console=detail check
```

BackTrace when running check command:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000417c29 in strZ (this=0x0) at ./common/type/string.h:144
144	    return ((const StringConst *)this)->buffer;
(gdb) bt
#0  0x0000000000417c29 in strZ (this=0x0) at ./common/type/string.h:144
#1  checkDbConfig (pgVersion=110000, dbIdx=1, dbObject=0xd2a548, isStandby=false) at command/check/common.c:66
#2  0x0000000000417684 in checkPrimary (dbGroup=...) at command/check/check.c:114
#3  0x0000000000417a1f in cmdCheck () at command/check/check.c:162
#4  0x000000000049cc2c in main (argListSize=4, argList=0x7fff0c61dea8) at main.c:144
```

### Backup command
```shell
pgbackrest --stanza=demo --log-level-console=detail backup
```

BackTrace when running backup command:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000417c29 in strZ (this=0x0) at ./common/type/string.h:144
144	    return ((const StringConst *)this)->buffer;
(gdb) bt
#0  0x0000000000417c29 in strZ (this=0x0) at ./common/type/string.h:144
#1  checkDbConfig (pgVersion=110000, dbIdx=1, dbObject=0x186b0a8, isStandby=false) at command/check/common.c:66
#2  0x000000000040fce5 in backupStart (backupData=0x185bf08) at command/backup/backup.c:867
#3  0x00000000004148af in cmdBackup () at command/backup/backup.c:1946
#4  0x000000000049cbe3 in main (argListSize=4, argList=0x7ffdbdebf488) at main.c:123
```

### The right set of privileges

After trial and error, I guess these are the privileges required for the backup_user.
Also please let me know if any of the privileges is extraneous or if anything is missing.
```sql
BEGIN;
CREATE ROLE backup_user WITH LOGIN;
GRANT USAGE ON SCHEMA pg_catalog TO backup_user;
GRANT EXECUTE ON FUNCTION pg_catalog.current_setting(text) TO backup_user;
GRANT EXECUTE ON FUNCTION pg_catalog.pg_is_in_recovery() TO backup_user;
GRANT EXECUTE ON FUNCTION pg_catalog.pg_start_backup(text, boolean, boolean) TO backup_user;
GRANT EXECUTE ON FUNCTION pg_catalog.pg_stop_backup(boolean, boolean) TO backup_user;
GRANT EXECUTE ON FUNCTION pg_catalog.pg_create_restore_point(text) TO backup_user;
GRANT EXECUTE ON FUNCTION pg_catalog.pg_switch_wal() TO backup_user;
GRANT EXECUTE ON FUNCTION pg_catalog.clock_timestamp() TO backup_user;
GRANT EXECUTE ON FUNCTION pg_catalog.pg_try_advisory_lock(bigint) TO backup_user;
GRANT EXECUTE ON FUNCTION pg_catalog.pg_walfile_name(pg_lsn) TO backup_user;
GRANT pg_read_all_settings to backup_user;
COMMIT;
```

### Configuration files and logs:
Backup server:
```
cat /etc/pgbackrest/pgbackrest.conf
[demo]
pg1-host=dbhost
pg1-socket-path=/tmp
pg1-path=/home/test/someDir/datadir
pg1-host-user=test
pg1-user=backup_user

[global]
repo-path=/home/test/someDir/pgbackrest/repo
start-fast=y

[global:backup]
process-max=3
```
DB Server:
```
cat /etc/pgbackrest/pgbackrest.conf
[demo]
pg1-path=/home/test/someDir/datadir
pg1-socket-path=/tmp
pg1-host-user=test
pg1-user=backup_user

[global]
repo1-host=backup-server
repo1-host-user=test
```

Logs from backup server while running backup command:
```
cat /var/log/pgbackrest/demo-backup.log
-------------------PROCESS START-------------------
2020-09-16 12:09:45.562 P00   INFO: backup command begin 2.29: --log-level-console=debug --pg1-host=dbhost --pg1-host-user=test --pg1-path=/home/test/someDir/datadir --pg1-socket-path=/tmp --pg1-user=backup_new --process-max=3 --repo1-path=/home/test/someDir/pgbackrest/repo --stanza=demo --start-fast
2020-09-16 12:09:45.562 P00   WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space
                                    HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.
2020-09-16 12:09:46.467 P00   INFO: last backup label = 20200915-133445F_20200915-140203I, version = 2.29
```

Postgres's log:
```log
2020-09-16 12:16:46.439 IST--xID=0 PID=22737--LOG:  statement: set search_path = 'pg_catalog'
2020-09-16 12:16:46.540 IST--xID=0 PID=22737--LOG:  statement: set client_encoding = 'UTF8'
2020-09-16 12:16:46.642 IST--xID=0 PID=22737--LOG:  statement: select (select setting from pg_catalog.pg_settings where name = 'server_version_num')::int4, (select setting from pg_catalog.pg_settings where name = 'data_directory')::text, (select setting from pg_catalog.pg_settings where name = 'archive_mode')::text, (select setting from pg_catalog.pg_settings where name = 'archive_command')::text
2020-09-16 12:16:46.743 IST--xID=0 PID=22737--LOG:  statement: set application_name = 'pgBackRest [backup]'
2020-09-16 12:16:46.744 IST--xID=0 PID=22737--LOG:  statement: set max_parallel_workers_per_gather = 0
2020-09-16 12:16:46.845 IST--xID=0 PID=22737--LOG:  statement: select pg_catalog.pg_is_in_recovery()
2020-09-16 12:16:46.951 IST--xID=0 PID=22737--LOG:  statement: select (extract(epoch from clock_timestamp()) * 1000)::bigint
```
My guess is this query returns null, which resulted in the error:
```
postgres=> select setting from pg_catalog.pg_settings where name = 'data_directory'::text;
 setting
---------
(0 rows)
```
And finally, log-level-console=debug's output is attached
[BackupDebugOut.txt](https://github.com/pgbackrest/pgbackrest/files/5230156/BackupDebugOut.txt)

**Comment by dwsteele** [comment]
Thank you for the detailed report! This used to give a rather unsatisfactory error like:
```
DbMismatchError: version '9.6' and path '(null)' queried from cluster do not match version '11' and '/home/vagrant/test/test-0/pg1' read from '/home/vagrant/test/test-0/pg1/global/pg_control'
    HINT: the pg1-path and pg1-port settings likely reference different clusters.
```
We've been meaning to improve the error it but meanwhile fbff2995 in 2.28 converted it into a segfault. See attached PR for a fix and better error message.

**Comment by insafk** [comment]
Thanks, David for the quick response.
